---
- name: Gather the package facts
  package_facts:
    manager: auto

- name: Create package component
  dci_component:
    name: "{{ item }} {{ ansible_facts.packages[item][0].version }}-{{ ansible_facts.packages[item][0].release }}"
    canonical_project_name: "{{ item }} {{ ansible_facts.packages[item][0].version }}-{{ ansible_facts.packages[item][0].release }}"
    team_id: "{{ job_info['job']['team_id'] }}"
    topic_id: "{{ job_info['job']['topic_id'] }}"
    type: rpm
    state: present
  register: package_component

- name: Attach package component to the job
  dci_job_component:
    component_id: " {{ package_component.component.id }} "
    job_id: " {{ job_id }} "
  register: job_component_result
  until: job_component_result is not failed
  retries: 5
  delay: 20
  when:
    - "'component' in package_component"
    - "'id' in package_component.component"
...
