---
- name: Install operators
  ansible.builtin.include_tasks: install_operator.yml
  vars:
    rhoai_op_name: "{{ item }}"
    rhoai_op_package: "{{ __rhoai_operator_map[item].package }}"
    rhoai_op_channel: "{{ __rhoai_operator_map[item].channel }}"
    rhoai_op_namespace: "{{ __rhoai_operator_map[item].namespace }}"
  loop:  # install has to be in order
    - servicemesh
    - serverless
    - rhods

- name: Create DataScienceCluster
  when: rhoai_create_dsc | bool
  community.kubernetes.k8s:
    state: present
    wait: "{{ rhoai_wait_for_dsc | bool }}"
    definition:
      apiVersion: datasciencecluster.opendatahub.io/v1
      kind: DataScienceCluster
      metadata:
        name: "{{ rhoai_dsc_name }}"
        labels:
          app.kubernetes.io/name: datasciencecluster
          app.kubernetes.io/instance: "{{ rhoai_dsc_name }}"
          app.kubernetes.io/part-of: "{{ __rhoai_operator_map.rhods.package }}"
          app.kubernetes.io/managed-by: kustomize
          app.kubernetes.io/created-by: "{{ __rhoai_operator_map.rhods.package }}"
      spec:
        components:
          codeflare:
            managementState: Removed
          kserve:
            serving:
              ingressGateway:
                certificate:
                  type: SelfSigned
              managementState: Managed
              name: knative-serving
            managementState: Managed
          ray:
            managementState: Removed
          kueue:
            managementState: Removed
          workbenches:
            managementState: Managed
          dashboard:
            managementState: Managed
          modelmeshserving:
            managementState: Managed
          datasciencepipelines:
            managementState: Managed
...
