---
# tasks file for jenkins-job-launcher
- name: Validate required variables
  ansible.builtin.assert:
    that:
      - jjl_username | string
      - jjl_token | string
      - jjl_job_params | string
      - jjl_job_url | string
    
- name: Trigger jenkins job
  ansible.builtin.uri:
    url: "{{ jjl_job_url }}/buildWithParameters/"
    method: POST
    validate_certs: false
    user: "{{ jjl_username }}"
    password: "{{ jjl_token }}"
    force_basic_auth: true
    body_format: "{{ jjl_body_format | default('form-urlencoded') }}"
    status_code: [200, 201]
    body: "{{ jjl_job_params }}"
    headers:
      Content-Type: application/x-www-form-urlencoded
  register: queue_build_number 

- name: Get jenkins build number
  ansible.builtin.uri:
    url: '{{ queue_build_number.location }}/api/json'
    method: GET
    validate_certs: false
    user: "{{ jjl_username }}"
    password: "{{ jjl_token }}"
  register: jenkins_build_number

- name: Wait for Jenkins status code
  ansible.builtin.uri:
    url: "{{ jenkins_build_number.json.executable.url }}/api/json"
    method: GET
    validate_certs: false
    user: "{{ jjl_username }}"
    password: "{{ jjl_token }}"
  register: in_progress
  until:
    - in_progress.json is defined
    - in_progress.json.inProgress is defined
    - not in_progress.json.inProgress | bool
  retries: 200
  delay: "{{ jjl_delay_seconds }}" # total of 3hrs 20 minutes.

- name: Fail if result is not SUCCESS
  ansible.builtin.fail:
    msg: job failed
  when: in_progress.json.result != "SUCCESS"
