---
preflight_image: "quay.io/opdev/preflight:1.6.10"
preflight_namespace: preflight-testing
preflight_sa: default
preflight_custom_ca: ""
preflight_podman_ca: ""
pyxis_url: "https://catalog.redhat.com/api/containers/v1"
preflight_test_certified_image: false
preflight_run_health_check: true
...
