---
preflight_image: "quay.io/opdev/preflight:1.9.6"
preflight_repo_https: "https://github.com/redhat-openshift-ecosystem/openshift-preflight"
preflight_namespace: preflight-testing
preflight_sa: default
preflight_custom_ca: ""
preflight_podman_ca: ""
catalog_url: "https://catalog.redhat.com/api/containers/v1"
preflight_test_certified_image: false
preflight_run_health_check: true
max_images_per_batch: 1
...
