---
- name: Check that organization_id is defined
  ansible.builtin.assert:
    that: "{{ organization_id }} is defined"

- name: Set Helm Chart project facts
  ansible.builtin.set_fact:
    chart_name: "{{ current_chart_name }}"

- name: Get certification Helm Chart projects for organization
  vars:
    pyxis_apikey: "{{ lookup('file', pyxis_apikey_path) }}"
  ansible.builtin.uri:
    url: >
      {{ catalog_url }}/vendors/org-id/{{ organization_id }}/projects/certification?filter=project_status%3D%3Dactive&page_size={{ page_size }}&page=0
    method: GET
    headers:
      X-API-KEY: "{{ pyxis_apikey }}"
    body_format: json
    status_code: 200
    timeout: 120
  register: cert_project_list_output
  retries: 20
  delay: 3
  until: not cert_project_list_output.failed

- name: Get certification projects information from organization using Helm Chart Name
  ansible.builtin.set_fact:
    helmchart_cert_project_data: "{{ cert_project_list_output.json.data | json_query(query_data) | unique }}"  # noqa: jinja[invalid]
  vars:
    query_data: "[?name == '{{ chart_name }}']"

- name: Set fact if chart is already in an active certification project
  ansible.builtin.set_fact:
    helmchart_cert_project_exists_own_org: true
  loop: "{{ helmchart_cert_project_data }}"
  loop_control:
    label: "{{ item._id }}"
  when:
    - helmchart_cert_project_data | default([]) | length > 0
    - item.name == chart_name
    - item.type == "Helm Chart"
    - item.project_status == "active"

- name: Notify if Helm Chart is already in an active certification project
  ansible.builtin.debug:
    msg:
      - "Helm Chart Name {{ chart_name }} is in process to get certify in another project of this organization"
      - "Review the following projects: {{ item._id }}"
      - "To continue archive the project or reach out to support to delete it."
  loop: "{{ helmchart_cert_project_data }}"
  loop_control:
    label: "{{ item._id }}"
  when:
    - helmchart_cert_project_exists_own_org | default(false) | bool
    - item.name == chart_name
    - item.type == "Helm Chart"
    - item.project_status == "active"

- name: Set project ID to reuse it later
  ansible.builtin.set_fact:
    helm_project_id: "{{ item._id }}"
  loop: "{{ helmchart_cert_project_data }}"
  loop_control:
    label: "{{ item._id }}"
  when:
    - helmchart_cert_project_exists_own_org | default(false) | bool
    - helmchart_cert_project_data | default([]) | length > 0
    - item.type == 'Helm Chart'
    - item.name == chart_name
...
