---
- name: Validate cert_settings for container project
  ansible.builtin.assert:
    that: "{{ item }} is defined"
    fail_msg: "The parameter {{ item }} is required to update cert project"
    success_msg: "The parameter {{ item }} is present"
  with_items:
    - cert_item.short_description
    - cert_item.short_description | length >= 50
    - cert_settings.auto_publish
    - cert_settings.email_address
    - cert_settings.build_categories
    - cert_settings.registry_override_instruct
    - cert_settings.application_categories
    - cert_settings.os_content_type
    - cert_settings.privileged
    - cert_settings.release_category
    - cert_settings.repository_description
  when: product_type == 'container'

- name: Validate cert_settings for operator project
  ansible.builtin.assert:
    that: "{{ item }} is defined"
    fail_msg: "The parameter {{ item }} is required to update cert project"
    success_msg: "The parameter {{ item }} is present"
  with_items:
    - cert_item.short_description
    - cert_item.short_description | length >= 50
    - cert_settings.auto_publish
    - cert_settings.email_address
    - cert_settings.registry_override_instruct
    - cert_settings.application_categories
    - cert_settings.privileged
    - cert_settings.repository_description
  when: product_type == 'operator'

- name: Validate cert_settings for Helm Chart project
  ansible.builtin.assert:
    that: "{{ item }} is defined"
    fail_msg: "The parameter {{ item }} is required to update cert project"
    success_msg: "The parameter {{ item }} is present"
  with_items:
    - helmchart.short_description
    - helmchart.short_description | length >= 50
    - cert_settings.long_description
    - cert_settings.email_address
    - cert_settings.distribution_method
    - cert_settings.application_categories
    - cert_settings.distribution_instructions
    - cert_settings.github_usernames
  when: product_type == 'helmchart'
...
