num_samples: "{{ multibench_sample | default('3') }}"
multibench_tags:
  automation: ansible
multibench_script_dir: "/root/crucible-examples/multibench/openshift/example-A/daily"
multibench_script: "run.sh"
