num_samples: "{{ multibench_sample | default('3') }}"
multibench_tags:
  automation: ansible
multibench_script_dir: "/root/crucible-examples/multibench/openshift/example-A/daily"
multibench_script: "run.sh"

# Crucible metric collection (used after run when result-summary is available)
multibench_crucible_metric_source: "mpstat"
multibench_crucible_metric_type: "Busy-CPU"
multibench_crucible_metric_breakout: "hostname=worker-3,num"
multibench_crucible_metric_filename: "crucible-metric-mpstat-busy-cpu.txt"
