---
- name: "Delete MetalLB BGP Peers"
  community.kubernetes.k8s:
    state: absent
    api: metallb.io/v1beta2
    kind: BGPPeer
    name: "{{ peer.name }}"
    namespace: "{{ mlb_namespace }}"
    wait: true
    wait_condition:
      status: False
    wait_sleep: 2
    wait_timeout: 300
  loop: "{{ mlb_bgp_peers }}"
  loop_control:
    loop_var: peer
  when:
    - mlb_bgp_peers is defined

- name: "Delete MetalLB resources"
  community.kubernetes.k8s:
    state: absent
    api: "{{ resource.apiVer }}"
    kind: "{{ resource.kind }}"
    name: "{{ resource.name }}"
    namespace: "{{ mlb_namespace }}"
    wait: true
    wait_condition:
      status: False
    wait_sleep: 2
    wait_timeout: 300
  loop: "{{ mlb_bgp_peers }}"
  ignore_errors: true
  # loop: "{{ mlb_resources }}"
  loop_control:
    loop_var: resource
