---
- name: "Configure MetalLB resources"
  when:
    - mlb_action == 'install'
  block:
    - name: "Validate required variables"
      ansible.builtin.include_tasks: pre-requisites.yml

    - name: "Set up MetalLB resources"
      ansible.builtin.include_tasks: setup-metallb.yml

- name: "Cleanup MetalLB resources"
  ansible.builtin.include_tasks: clean-resources.yml
  when:
    - mlb_action == 'cleanup'
...
