---
- name: "Check if the main MetalLB CRD is present"
  kubernetes.core.k8s_info:
    kind: CustomResourceDefinition
    name: metallbs.metallb.io
  register: metal_crd
  no_log: true

- name: "Fail if MetalLB CRD is not present"
  ansible.builtin.fail:
    msg: "MetalLB CRD are not present, please install the MetalLB operator in the ACM hub"
  when: metal_crd.resources | list | count == 0

- name: "Check for metallb instances"
  kubernetes.core.k8s_info:
    api_version: metallb.io/v1beta1
    kind: MetalLB
  register: mlb_instance

- name: "Check if a metallb instance already exists"
  ansible.builtin.debug:
    msg: >
      A MetalLB instance already exists in this cluster, it will be updated
      accordingly
  when:
    - mlb_instance.resources | length == 1

- name: "Check mlb_settings file exits"
  ansible.builtin.stat:
    path: "{{ mlb_settings }}"
  register: file_stat
  when:
    - mlb_settings is defined
    - mlb_settings | default("") | length

- name: "Load mlb_settings from vars file"
  ansible.builtin.include_vars:
    file: "{{ mlb_settings }}"
  when:
    - file_stat is defined
    - file_stat.stat is defined
    - file_stat.stat.exists | bool

- name: "Validate parameters are defined"
  ansible.builtin.assert:
    that: "{{ item }} is defined"
    fail_msg: "The parameter {{ item }} is required. See README.md for more details"
  loop:
    - mlb_ipaddr_pool

- name: "Validate values of mlb_wait_* are positive integers"
  ansible.builtin.assert:
    that:
      - mlb_wait_delay | int > 0
      - mlb_wait_retries | int > 0
    fail_msg: "The parameters mlb_wait_delay and mlb_wait_retries must both be integers"

- name: "Confirm that MetalLB controller pods are Running"
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Pod
    namespace: "{{ mlb_namespace }}"
    label_selectors:
      - control-plane = controller-manager
  register: pod_list
  until: pod_list|json_query('resources[*].status.phase')|unique == ["Running"]
  retries: "{{ mlb_wait_retries }}"
  delay: "{{ mlb_wait_delay }}"
  no_log: true

- name: "Validate parameter mlb_ipaddr_pool is a list"
  ansible.builtin.assert:
    that: "{{ mlb_ipaddr_pool }} is iterable"
    fail_msg: "The parameter {{ mlb_ipaddr_pool }} is required to be a list"

- name: "Validate values of mlb_bgp_peers are defined"
  ansible.builtin.assert:
    that:
      - peer.name is defined
      - peer.address is defined
      - peer.remote_asn is defined
      - peer.local_asn is defined
    fail_msg: "A value in the mlb_bgp_peers list is missing. See role README.md for details"
  loop: "{{ mlb_bgp_peers }}"
  loop_control:
    loop_var: peer
  when:
    - mlb_bgp_peers is defined

- name: "Get cluster version"
  kubernetes.core.k8s_info:
    api: config.openshift.io/v1
    kind: ClusterVersion
    name: version
  register: cluster_version
  no_log: true

- name: "Fail when OCP version is not supported"
  vars:
    current_ver_query: "history[?state=='Completed'] | [0].version"
    full_ver: "{{ cluster_version.resources[0].status | json_query(current_ver_query) }}"  # noqa: jinja[invalid]
    current_ver: "{{ full_ver.split('-')[0] }}"
    ocp_version: "{{ current_ver }}"
  ansible.builtin.fail:
    msg: "OCP version must be >= {{ mlb_ocp_supported }}"
  when: ocp_version is version( mlb_ocp_supported , "<")
...
