---
- name: Setup tmp scorecard folders
  block:
    - name: Set directories for artifacts and operator bundle extract
      set_fact:
        scorecard_artifacts: "{{ scorecard_tmp_dir.path }}/artifacts"
        scorecard_operator_dir: "{{ scorecard_tmp_dir.path }}/scorecard_operator_dir"

    - name: Create nested directories for artifacts and operator bundle extract
      file:
        path: "{{ scorecard_dir_to_create }}"
        state: directory
        mode: 0744
      loop:
        - "{{ scorecard_artifacts }}"
        - "{{ scorecard_operator_dir }}"
      loop_control:
        loop_var: scorecard_dir_to_create

- name: Extract operator bundle
  block:
    - name: Extract operator bundle and add read permissions
      shell:
        cmd: |
          {{ scorecard_oc_tool_path }} image extract {{ operator.bundle_image }} --confirm -a {{ scorecard_partner_creds }}
          chmod -R go+r ./
        chdir: "{{ scorecard_operator_dir }}"

    - name: Print extracted operator data
      shell: |
        tree "{{ scorecard_operator_dir }}"
      ignore_errors: true

# In the disconnected env, the catalog is generated by mirroring role
- name: Retrieve operator index image in the connected environment
  set_fact:
    OO_INDEX: "{{ operator.index_image }}"
  when: not scorecard_dci_disconnected | default(false) | bool

- name: Template scorecard config
  template:
    src: templates/scorecard-test-config.yaml.j2
    dest: "{{ scorecard_artifacts }}/scorecard-test-config.yaml"

- name: Set path to scorecard config
  set_fact:
    scorecard_config_path: "{{ scorecard_artifacts }}/scorecard-test-config.yaml"

- name: Create namespace for scorecard testing
  community.kubernetes.k8s:
    state: present
    definition:
      api_version: v1
      kind: Namespace
      metadata:
        name: "{{ scorecard_namespace }}"
        labels:
          security.openshift.io/scc.podSecurityLabelSync: "false"
          pod-security.kubernetes.io/enforce: "baseline"
          pod-security.kubernetes.io/warn: "baseline"

- name: Set prefix for scorecard output files
  vars:
    operator_name: "{{ operator.bundle_image.split('@')[0].split('/')[-1] }}"
  set_fact:
    scorecard_prefix: "scorecard_{{ operator_name }}"

- block:
    - name: Run operator-sdk scorecard --selector=test=basic-check-spec-test
      environment:
        - OPENSHIFT_AUTH: "{{ scorecard_partner_creds }}"
        - OO_BUNDLE: "{{ operator.bundle_image }}"
        - OO_INDEX: "{{ OO_INDEX }}"
        - ARTIFACT_DIR: "{{ scorecard_artifacts }}"
      shell:
        cmd: >
          ./operator-sdk scorecard
          --output xunit
          --selector=test=basic-check-spec-test
          --kubeconfig "{{ scorecard_kubeconfig_path }}"
          --namespace {{ scorecard_namespace }}
          --service-account default
          --config {{ scorecard_config_path }}
          --verbose
          --wait-time 300s
          "{{ scorecard_operator_dir }}"
        chdir: "{{ scorecard_tmp_dir.path }}"
      register: scorecard_exec
  rescue:
    - name: Get Scorecard pods
      community.kubernetes.k8s_info:
        kind: Pod
        namespace: "{{ scorecard_namespace }}"
      register: scorecard_pods

    - name: Get scorecard-related events
      community.kubernetes.k8s_info:
        kind: Event
        namespace: "{{ scorecard_namespace }}"
      register: scorecard_events

    - name: Dump scorecard errors into logs
      template:
        src: templates/scorecard-errors-basic-check-spec-test.j2
        dest: "{{ scorecard_job_logs.path }}/{{ scorecard_prefix }}_errors_basic_check_spec_test.json"

- name: Copy scorecard basic-check-spec-test output into logs
  copy:
    content: "{{ scorecard_exec.stdout }}"
    dest: "{{ scorecard_job_logs.path }}/{{ scorecard_prefix }}_basic_check_spec_test.xml"

- name: Run operator-sdk scorecard --selector=suite=olm
  environment:
    - OPENSHIFT_AUTH: "{{ scorecard_partner_creds }}"
    - OO_BUNDLE: "{{ operator.bundle_image }}"
    - OO_INDEX: "{{ OO_INDEX }}"
    - ARTIFACT_DIR: "{{ scorecard_artifacts }}"
  shell:
    cmd: >
      ./operator-sdk scorecard
      --output xunit
      --selector=suite=olm
      --kubeconfig "{{ scorecard_kubeconfig_path }}"
      --namespace {{ scorecard_namespace }}
      --service-account default
      --config {{ scorecard_config_path }}
      --verbose
      --wait-time 300s
      "{{ scorecard_operator_dir }}"
    chdir: "{{ scorecard_tmp_dir.path }}"
  register: scorecard_exec
  ignore_errors: true

- name: Copy scorecard basic-check-spec-test output into logs
  copy:
    content: "{{ scorecard_exec.stdout }}"
    dest: "{{ scorecard_job_logs.path }}/{{ scorecard_prefix }}_suite_olm.xml"

- name: Delete namespace used for scorecard testing
  community.kubernetes.k8s:
    name: "{{ scorecard_namespace }}"
    api_version: v1
    kind: Namespace
    state: absent

- name: Delete nested directories for artifacts and operator bundle extract
  file:
    path: "{{ scorecard_dir_to_del }}"
    state: absent
  loop:
    - "{{ scorecard_artifacts }}"
    - "{{ scorecard_operator_dir }}"
  loop_control:
    loop_var: scorecard_dir_to_del
...
