---
galaxy_info:
  author: Red Hat CI
  description: Gather node hardware and kernel information from OpenShift cluster
  license: Apache-2.0
  min_ansible_version: "2.9"

  platforms:
    - name: EL
      versions:
        - "8"
        - "9"

  galaxy_tags:
    - openshift
    - kubernetes
    - hardware
    - diagnostics

dependencies: []
...
