---
- name: "Set Logs path"
  ansible.builtin.set_fact:
    ts_log_dir: "{{ job_logs.path | default('/tmp') }}"

- name: "Checking if all nodes in MCP are updated and ready before running RedHat tests"
  ansible.builtin.include_role:
    name: redhatci.ocp.check_resource
  vars:
    resource_to_check: "MachineConfigPool"
    check_wait_retries: 30
    check_wait_delay: 10

- name: "redhat_tests : Run openshift conformance tests"  # noqa: name[casing]
  ansible.builtin.include_tasks: conformance.yml
  tags:
    - conformance
  when:
    - ts_conformance_tests | string | length > 0
    - ts_registry_certificate is defined

- name: "redhat_tests : Run openshift CSI driver tests"  # noqa: name[casing]
  ansible.builtin.include_tasks: csi-tests.yml
  tags:
    - csi-tests
  when:
    - ts_csi_test_manifest | string | length > 0

- name: "redhat_tests : Run openshift CNI tests suites"  # noqa: name[casing]
  ansible.builtin.include_tasks: cni-tests.yml
  tags:
    - cni-tests
  when:
    - ts_do_cni_tests | default(false) | bool

- name: Validate if the kubevirt CRD is present
  kubernetes.core.k8s_info:
    api_version: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    kubeconfig: "{{ kubeconfig_path }}"
    name: kubevirts.kubevirt.io
  register: virtscrdstatus

- name: "redhat_tests : Run openshift Virtualization tests suites - kubevirt-hyperconverged is required"  # noqa: name[casing]
  ansible.builtin.include_tasks: kubevirt-tests.yml
  tags:
    - virtualization-tests
  when:
    - ts_do_virt_tests | default(false) | bool
    - virtscrdstatus.resources|length > 0
...
