---
# Forgejo configuration defaults
fs_state: present
fs_user: "{{ ansible_user_id }}"
fs_user_home: "{{ ansible_user_dir }}"
fs_user_uid: "{{ ansible_user_uid }}"
fs_user_gid: "{{ ansible_user_gid }}"
fs_base_dir: "{{ ansible_env.HOME }}/forgejo"
fs_data_dir: "{{ fs_base_dir }}/data"
fs_db_dir: "{{ fs_base_dir }}/db"
fs_db_container_dir: "/var/lib/postgresql/18/docker"
fs_server_domain: localhost
fs_use_systemd: false

# Container configuration
fs_app_image: codeberg.org/forgejo/forgejo:13
fs_postgres_image: mirror.gcr.io/library/postgres:18

# Pod configuration
fs_pod_name: forgejo
fs_pod_http_port: 3000
fs_pod_ssh_port: 2222

# Database configuration
fs_db_user: forgejo
fs_db_name: forgejo
fs_db_port: 5432
fs_db_container_name: db

# Application configuration
fs_app_user: forgejo
fs_app_email: "{{ fs_app_user }}@{{ fs_server_domain }}"
fs_app_container_name: forgejo
fs_app_name: "Forgejo: Beyond coding. We forge."

# Additional application environment variables
fs_app_env_vars: {}
# Example:
# fs_app_env_vars:
#   FORGEJO__server__DOMAIN: git.example.com
#   FORGEJO__server__ROOT_URL: https://git.example.com

# Waiting times
fs_wait_retries: 30
fs_wait_delay: 10
