---
# Depending on "resource_to_check" variable, do one check or another
# Wrapping the checks in a block to be able to use "delegate_to: localhost" clause
- name: Do the check
  block:
    # Check MCP application
    - name: Check MCP application
      include_tasks:
        file: wait-mcp.yml
        apply:
          environment:
            KUBECONFIG: "{{ kubeconfig_path }}"
      when: resource_to_check == "MachineConfigPool"

    # Check SriovNetworkNodeState application
    - name: Check SriovNetworkNodeState application
      include_tasks:
        file: wait-sriov.yml
        apply:
          environment:
            KUBECONFIG: "{{ kubeconfig_path }}"
      when: resource_to_check == "SriovNetworkNodeState"
  delegate_to: localhost

# If reached this point, the check passed, so reinitialize retry_count for future executions,
# as this is a shared role
- name: Reinitialize the retry count
  set_fact:
    retry_count: 1
...
