# The mirror_list  should come from inventory or settings
- name: Basic facts
  set_fact:
    base_version: "{{ version.split('.')[0] }}.{{ version.split('.')[1] }}"
    manifests_dir: "redhat-operators-manifests"
    opm_catalog_source_name: "{{ opm_catalog_source_name }}"
    opm_catalog_source_namespace: "{{ opm_catalog_source_namespace }}"
    opm_catalog_source_displayname: "{{ opm_catalog_source_displayname }}"
    opm_local_registry_path: "{{ opm_local_registry_path }}"

- name: Set facts for newer ocp versions
  set_fact:
    opm_local_registry_path: "/redhat/redhat-operator-index"
  when:
    - version is version("4.6.17", ">=")
