---
hub_disable_selfmanagement: false
hub_availability: High
hub_instance: multiclusterhub
hub_namespace: open-cluster-management
hub_disconnected: false
hub_hugepages_type: hugepages-2Mi
hub_hugepages_size: 1024Mi
hub_db_volume_size: 40Gi
hub_fs_volume_size: 50Gi
hub_img_volume_size: 80Gi
hub_vm_external_network: true
hub_img_svc_skip_tls_verify: false
...
