---

- name: "Clone opcap repository"
  git:
    repo: "{{ opcap_repo }}"
    dest: "{{ opcap_dir.path }}/opcap"

# Launching a container to build the GO bin
# Dir where the repo has been cloned is bound as a volume (with option Z for SELinux compatibility)
- name: "run podman build"
  containers.podman.podman_container:
    name: go-builder
    image: "golang:1.19"
    debug: true
    log_level: "info"
    command: make -C /opcap build OPCAP_VERSION={{ opcap_version }}
    detach: false
    rm: true
    volume:
      - "{{ opcap_dir.path }}/opcap/:/opcap:Z"
  register: opcap_build
  retries: 4
  delay: 10
  until: opcap_build is not failed

- name: "Check opcap bin"
  shell:
    cmd: >
      ./bin/opcap version
    chdir: "{{ opcap_dir.path }}/opcap"

...