---
rhoai_action: install
rhoai_operator_map: {}
rhoai_source_catalog: redhat-operators
rhoai_source_namespace: openshift-marketplace
rhoai_create_dsc: true
rhoai_dsc_name: default-dsc
rhoai_wait_for_dsc: true
...
