---
- name: "Render bundle operator image"
  vars:
    opm_auths: "/usr/share/dci-openshift-agent/utils/opm-auths"
  ansible.builtin.shell: >
    {% if partner_creds | length %}
    DOCKER_CONFIG={{ preflight_tmp_dir.path }}
    {% endif %}
    {{ opm_auths }}
    {{ opm_tool_path }} render {{ operator.bundle_image }}
  register: rendered_bundle
  retries: 2
  delay: 10
  until: rendered_bundle.rc == 0

- name: "Get inspected data"
  ansible.builtin.set_fact:
    bundle_data: "{{ rendered_bundle.stdout | from_json }}"

- name: "Get operator name, version and image data blob"
  vars:
    name_query: "properties[? type==`olm.package`].value.packageName"
    version_query: "properties[? type==`olm.package`].value.version"
    related_images: "{{ bundle_data | json_query('relatedImages[*].image') }}"
  ansible.builtin.set_fact:
    operator_name: "{{ bundle_data | json_query('name') | join('') }}"
    short_name: "{{ bundle_data | json_query(name_query) | join('') }}"
    operator_version: "{{ bundle_data | json_query(version_query) | join('') }}"
    operator_images: "{{ related_images | reject('search', operator.bundle_image) | list }}"

- name: "Fail when cluster is disconnected and operator images are not using a digest"
  ansible.builtin.fail:
    msg: "Operator images are not using a digest: {{ operator_images }}"
  when:
    - image | regex_search('.*@sha256:.*') == none
    - dci_disconnected | default(false) | bool
  loop: "{{ operator_images }}"
  loop_control:
    loop_var: image

- name: "Append data to the list of operators to check"
  vars:
    operator_to_check:
      name: "{{ short_name }}"
      operator_name: "{{ operator_name }}"
      version: "{{ operator_version }}"
      operator_images: "{{ operator_images }}"
      bundle_image: "{{ operator.bundle_image }}"
      index_image: "{{ operator.index_image | default(omit) }}"
      pyxis_container_identifier: "{{ operator.pyxis_container_identifier | default(omit) }}"
      pyxis_operator_identifier: "{{ operator.pyxis_operator_identifier | default(omit) }}"
      create_container_project: "{{ operator.create_container_project | default(omit) }}"
      create_operator_project: "{{ operator.create_operator_project | default(omit) }}"
      create_pr: "{{ operator.create_pr | default(omit) }}"
      merge_pr: "{{ operator.merge_pr | default(omit) }}"
      short_description: "{{ operator.short_description | default(omit) }}"
      attach_product_listing: "{{ operator.attach_product_listing | default(omit) }}"
  ansible.builtin.set_fact:
    preflight_operators_to_check: "{{ preflight_operators_to_check + [operator_to_check] }}"
