---
- name: Image Digest cleanup
  when: preflight_is_file is defined
  block:
    - name: Delete Image Source from cluster
      community.kubernetes.k8s:
        state: absent
        definition: "{{ lookup('file', preflight_is_file) }}"

    - name: Wait for MCP status
      ansible.builtin.include_role:
        name: redhatci.ocp.check_resource
      vars:
        resource_to_check: "MachineConfigPool"
        check_wait_retries: 90
        check_wait_delay: 30

    - name: Remove preflight Image Source file
      ansible.builtin.file:
        path: "{{ preflight_is_file }}"
        state: absent

- name: Remove tmp directory
  ansible.builtin.file:
    path: "{{ preflight_tmp_dir.path }}"
    state: absent
  when: preflight_tmp_dir is defined

- name: Remove certificate used by preflight from the CA-Trust database
  when: preflight_custom_ca | length
  become: true
  block:
    - name: Remove the anchor CA file
      ansible.builtin.file:
        state: absent
        path: "/etc/pki/ca-trust/source/anchors/preflight_ca.crt"

    - name: Update trusted CA
      ansible.builtin.command: /bin/update-ca-trust
...
