---
libvirt_image_path: /var/lib/libvirt/images
enable_conserver: false
bootmode: "{{ 'uefi' if enable_redfish else 'legacy' }}"
enable_legacy_vga_mode: false
do_dns_config: true
apps_ip_address: 192.168.123.10
api_ip_address: 192.168.123.5
dns_vip_address: 192.168.123.6

# REDFISH
enable_redfish: false
enable_virtualmedia: false
redfish_port: 8082
ocp_on_libvirt_repo_root_path: /tmp
ocp_on_libvirt_cert_country: US
ocp_on_libvirt_cert_state: MA
ocp_on_libvirt_cert_locality: Westford
ocp_on_libvirt_cert_organization: DCI
ocp_on_libvirt_cert_organizational_unit: Lab

...
