---
- name: Download stable openshift client
  vars:
    ocp_client_url: >
      https://mirror.openshift.com/pub/openshift-v4/
      x86_64/clients/ocp/stable/openshift-client-linux-amd64-rhel/
      {{ ansible_distribution_major_version }}.tar.gz
  ansible.builtin.unarchive:
    src: "{{ ocp_client_url }}"
    dest: "{{ ah_tmp_dir }}"
    remote_src: true
    mode: "0755"
  register: result
  retries: 3
  delay: 10
  until: result is not failed

- name: Get route for hcp-cli
  community.kubernetes.k8s_info:
    kind: Route
    name: hcp-cli-download
    namespace: multicluster-engine
  register: ah_route
  until: ah_route.resources | length
  retries: 10
  delay: 10

- name: Download hcp cli tarball, ignoring the certificate
  vars:
    ah_arch: amd64
  ansible.builtin.unarchive:
    src: "https://{{ ah_route.resources[0].spec.host }}/linux/{{ ah_arch }}/hcp.tar.gz"
    dest: "{{ ah_tmp_dir }}"
    mode: "0755"
    remote_src: true
    validate_certs: false
  register: result
  retries: 3
  delay: 10
  until: result is not failed

- name: Get hcp cli version
  ansible.builtin.shell:
    cmd: >
      {{ ah_tmp_dir }}/hcp --version
  register: result
  changed_when: false

- name: Print hcp cli version
  ansible.builtin.debug:
    var: result.stdout

- name: Set hcp cli path
  ansible.builtin.set_fact:
    ah_hcp_cli_path: "{{ ah_tmp_dir }}/hcp"

- name: Set oc cli path
  ansible.builtin.set_fact:
    ah_oc_cli_path: "{{ ah_tmp_dir }}/oc"
...
