---
kbpc_check_commit_sha: false
kbpc_version: v5.4.9
kbpc_repo_org_name: redhat-best-practices-for-k8s
kbpc_project_name: certsuite
kbpc_repository: "https://github.com/{{ kbpc_repo_org_name }}/{{ kbpc_project_name }}"
kbpc_test_labels: "all"
kbpc_test_config:
  - namespace: ""
    targetpodlabels: []
    targetoperatorlabels: []
    target_crds: []
    exclude_connectivity_regexp: ""
kbpc_accepted_kernel_taints: []
kbpc_services_ignore_list: []
kbpc_allow_preflight_insecure: false
# CWE Hydra apikey for automated results submission
# It must be created manually in Connect UI
# Do not forget to define kbpc_cwe_project_id as well
kbpc_cwe_apikey_path: "/opt/cache/cwe-apikey.txt"
# If this is not set to true, JUnit file will not be created
kbpc_enable_xml_creation: true
kbpc_non_intrusive_only: false
kbpc_log_level: info
kbpc_postrun_delete_resources: true
kbpc_pullsecret: ""
kbpc_registry: ""
kbpc_partner_creds: ""
kbpc_image_name: certsuite
kbpc_image_suffix: "{{ lookup('community.general.random_string', length=16, special=false) }}"
kbpc_support_image_name: certsuite-probe
# Provide feedback for each certsuite test launched. Just copy this template and fill the value for the
# tests you want to provide feedback. You don't need to include the tests that you don't want to provide feedback.
# To insert line breaks, use \\n (you need to escape it). Same for quotes and so on.
# List of tests updated up to kbpc_version
kbpc_feedback:
  access-control-bpf-capability-check: ""
  access-control-cluster-role-bindings: ""
  access-control-container-host-port: ""
  access-control-crd-roles: ""
  access-control-ipc-lock-capability-check: ""
  access-control-namespace: ""
  access-control-namespace-resource-quota: ""
  access-control-net-admin-capability-check: ""
  access-control-net-raw-capability-check: ""
  access-control-no-1337-uid: ""
  access-control-one-process-per-container: ""
  access-control-pod-automount-service-account-token: ""
  access-control-pod-host-ipc: ""
  access-control-pod-host-network: ""
  access-control-pod-host-path: ""
  access-control-pod-host-pid: ""
  access-control-pod-role-bindings: ""
  access-control-pod-service-account: ""
  access-control-requests-and-limits: ""
  access-control-security-context: ""
  access-control-security-context-non-root-user-check: ""
  access-control-security-context-privilege-escalation: ""
  access-control-security-context-read-only-file-system: ""
  access-control-service-type: ""
  access-control-ssh-daemons: ""
  access-control-sys-admin-capability-check: ""
  access-control-sys-nice-realtime-capability: ""
  access-control-sys-ptrace-capability: ""
  affiliated-certification-container-is-certified-digest: ""
  affiliated-certification-helm-version: ""
  affiliated-certification-helmchart-is-certified: ""
  affiliated-certification-operator-is-certified: ""
  lifecycle-affinity-required-pods: ""
  lifecycle-container-poststart: ""
  lifecycle-container-prestop: ""
  lifecycle-cpu-isolation: ""
  lifecycle-crd-scaling: ""
  lifecycle-deployment-scaling: ""
  lifecycle-image-pull-policy: ""
  lifecycle-liveness-probe: ""
  lifecycle-persistent-volume-reclaim-policy: ""
  lifecycle-pod-high-availability: ""
  lifecycle-pod-owner-type: ""
  lifecycle-pod-recreation: ""
  lifecycle-pod-scheduling: ""
  lifecycle-pod-toleration-bypass: ""
  lifecycle-readiness-probe: ""
  lifecycle-startup-probe: ""
  lifecycle-statefulset-scaling: ""
  lifecycle-storage-provisioner: ""
  manageability-container-port-name-format: ""
  manageability-containers-image-tag: ""
  networking-dpdk-cpu-pinning-exec-probe: ""
  networking-dual-stack-service: ""
  networking-icmpv4-connectivity: ""
  networking-icmpv4-connectivity-multus: ""
  networking-icmpv6-connectivity: ""
  networking-icmpv6-connectivity-multus: ""
  networking-network-attachment-definition-sriov-mtu: ""
  networking-network-policy-deny-all: ""
  networking-ocp-reserved-ports-usage: ""
  networking-reserved-partner-ports: ""
  networking-restart-on-reboot-sriov-pod: ""
  networking-undeclared-container-ports-usage: ""
  observability-compatibility-with-next-ocp-release: ""
  observability-container-logging: ""
  observability-crd-status: ""
  observability-pod-disruption-budget: ""
  observability-termination-policy: ""
  operator-catalogsource-bundle-count: ""
  operator-crd-openapi-schema: ""
  operator-crd-versioning: ""
  operator-install-source: ""
  operator-install-status-no-privileges: ""
  operator-install-status-succeeded: ""
  operator-multiple-same-operators: ""
  operator-olm-skip-range: ""
  operator-pods-no-hugepages: ""
  operator-semantic-versioning: ""
  operator-single-crd-owner: ""
  operator-single-or-multi-namespaced-allowed-in-tenant-namespaces: ""
  performance-exclusive-cpu-pool: ""
  performance-exclusive-cpu-pool-rt-scheduling-policy: ""
  performance-isolated-cpu-pool-rt-scheduling-policy: ""
  performance-max-resources-exec-probes: ""
  performance-rt-apps-no-exec-probes: ""
  performance-shared-cpu-pool-non-rt-scheduling-policy: ""
  platform-alteration-base-image: ""
  platform-alteration-boot-params: ""
  platform-alteration-cluster-operator-health: ""
  platform-alteration-hugepages-1g-only: ""
  platform-alteration-hugepages-2m-only: ""
  platform-alteration-hugepages-config: ""
  platform-alteration-hyperthread-enable: ""
  platform-alteration-is-selinux-enforcing: ""
  platform-alteration-isredhat-release: ""
  platform-alteration-ocp-lifecycle: ""
  platform-alteration-ocp-node-os-lifecycle: ""
  platform-alteration-service-mesh-usage: ""
  platform-alteration-sysctl-config: ""
  platform-alteration-tainted-node-kernel: ""
